### ISSUE TITLE
weather does not work

### ISSUE THREAD

**Issue by IngeniousCoder** [IngeniousApplications/Travellite-Issues#8]
**Describe the bug**
Weather feature doesnt work

**To Reproduce**
1. Go to standard features dropdown
2. Select "Singapore"
3. Press search

**Expected behavior**
Comes out

V0.13

**Comment by IngeniousCoder** [comment]
after app crashes due to the above issue, all data is wiped.

By all data, i mean : 
- license status
- all trip data
- new user data (the welcome screen shows again)

**Comment by IngeniousCoder** [comment]
**Describe the bug**
weather does not work

**To Reproduce**
Steps to reproduce the behavior:
1. Go to weather information
2. type 'singapore' in select city field
3. press search



V0.21 Beta

**Comment by IngeniousCoder** [comment]
UI problem.
solved issue, I think UI needs to implement clearer instructions

**Comment by RichtigSauer** [comment]
Will update my help request document. Currently i postpone it cos idw Keep updating it after every update so i will update it after almost everything is done w TTP

**Comment by IngeniousCoder** [comment]
noted with thanks.

this will remain here for the public to report issues as always.
